[profile.default]
src = 'contracts'
out = 'build/contracts/foundry'
libs = ['lib']
test = "tests"
auto_detect_solc = true

#openzeppelin contract upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "build/contracts/foundry" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
#                   Paste TENDERLY_ACCESS_KEY    Chain ID        Verifier URL: ${TENDERLY_VIRTUAL_TESTNET_RPC}/verify/etherscan
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 73571, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan" }